name: CI
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v6
      - name: Run Tests
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test
